name: build digital-subscription-authorisation
on:
  push
jobs:
  contributions-store-retention-policy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # needed by actions-riff-raff
      contents: read # needed because the repo is private
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: Configure AWS credentials # needed by actions-riff-raff
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.GU_RIFF_RAFF_ROLE_ARN }}
          aws-region: eu-west-1
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache: yarn
      - name: build
        run: |
          yarn install
          yarn install --production --modules-folder dist/node_modules
          npx babel src -d dist
          cd dist
          zip -r digital-subscription-authorisation.zip *
          ls -al
      - name: Upload to Riff-Raff
        uses: guardian/actions-riff-raff@v2
        with:
          projectName: "subscriptions::digital-subscription-authorisation"
          buildNumberOffset: 1
          configPath: riff-raff.yaml
          contentDirectories: |
            digital-subscription-authorisation:
              - dist/digital-subscription-authorisation.zip

